name: Auto Crawling

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 00:00 执行

jobs:
  crawl_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.1'  # 使用你的 R 版本

      - name: Install packages
        run: |
          R -e "install.packages('rvest')"  # 安装需要的 R 包

      - name: Run crawler
        run: taipei_tenperature.R  # 运行你的爬虫脚本

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
