name: Setup R Environment
on: [push]
jobs:
  setup-r:
    runs-on: ubuntu-latest
    
    steps:
 name: Checkout code
 uses: actions/checkout@v2
    
 name: Set up R
 uses: r-lib/actions/setup-r@v1
      with:
        r-version: '4.0'  # 選擇所需的R版本

name: Install dependencies
      run: |
          - name: Install packages # 安装需要的 R 包
        run: |
          R -e "install.packages('rvest')"
          R -e "install.packages('httr')"
          R -e "install.packages('tidyverse')"
          R -e "install.packages('jsonlite')"
          R -e "library(httr)"
          R -e "library(rvest)"
          R -e "library(tidyverse)"
          R -e "library(jsonlite)"


name: Auto Crawling

on:
  schedule:
    - cron: '0 * * * *'  # 每天 UTC 时间 00:00 执行

jobs:
  crawl_job:
          
      - name: Run crawler
        run: taipei_tenperature.R  # 运行你的爬虫脚本

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
